import type { ModuleDetails } from "./course-types";

export const moduleDetails: Record<string, ModuleDetails> = {
  "cloud-foundations": {
    estimatedTime: { fr: "45 minutes", en: "45 minutes" },
    objectives: {
      fr: [
        "Identifier la hierarchie organization, folder, project et resource.",
        "Distinguer project name, project ID et project number.",
        "Appliquer le moindre privilege avec les roles IAM."
      ],
      en: [
        "Identify the organization, folder, project, and resource hierarchy.",
        "Distinguish project name, project ID, and project number.",
        "Apply least privilege with IAM roles."
      ]
    },
    prerequisites: {
      fr: [
        "Savoir naviguer dans la console Google Cloud.",
        "Comprendre la difference entre utilisateur, groupe et service account."
      ],
      en: [
        "Know how to navigate the Google Cloud Console.",
        "Understand the difference between a user, group, and service account."
      ]
    },
    lessonSections: [
      {
        id: "resource-hierarchy",
        title: { fr: "Hierarchie des ressources", en: "Resource hierarchy" },
        body: {
          fr: "Google Cloud organise les ressources de haut en bas: organisation, dossiers, projets, puis ressources. Le projet est le conteneur operationnel: il porte les API activees, les quotas, les roles IAM, les logs et la facturation.",
          en: "Google Cloud organizes resources top-down: organization, folders, projects, then resources. The project is the operational container: it carries enabled APIs, quotas, IAM roles, logs, and billing."
        },
        bullets: {
          fr: [
            "Le project ID est unique et permanent apres creation.",
            "Le project number est genere par Google et sert souvent aux integrations.",
            "Les folders servent a appliquer une gouvernance commune a plusieurs projets."
          ],
          en: [
            "The project ID is unique and permanent after creation.",
            "The project number is generated by Google and often used by integrations.",
            "Folders help apply shared governance across projects."
          ]
        }
      },
      {
        id: "iam-model",
        title: { fr: "Modele IAM", en: "IAM model" },
        body: {
          fr: "IAM repond a trois questions: qui agit, sur quelle ressource et avec quelles permissions. Les roles basic sont larges, les roles predefined sont plus precis, et les roles custom doivent rester controles.",
          en: "IAM answers three questions: who acts, on which resource, and with which permissions. Basic roles are broad, predefined roles are more precise, and custom roles must remain controlled."
        },
        bullets: {
          fr: [
            "Viewer peut lire, Editor peut modifier, Owner peut administrer largement.",
            "Un service account represente une application ou une VM, pas une personne.",
            "Les conditions IAM ajoutent un contexte: temps, ressource, attributs."
          ],
          en: [
            "Viewer can read, Editor can modify, Owner can broadly administer.",
            "A service account represents an application or VM, not a person.",
            "IAM conditions add context: time, resource, attributes."
          ]
        }
      },
      {
        id: "operational-rules",
        title: { fr: "Regles operationnelles", en: "Operational rules" },
        body: {
          fr: "Un bon projet de lab se nettoie vite, mais un projet production doit etre traçable. Nomme clairement les ressources, active seulement les API necessaires et garde une separation entre dev, test et production.",
          en: "A lab project must be easy to clean up, but a production project must be traceable. Name resources clearly, enable only necessary APIs, and separate dev, test, and production."
        },
        bullets: {
          fr: [
            "Ne jamais utiliser un compte personnel pour un lab temporaire.",
            "Eviter les roles Owner et Editor hors administration stricte.",
            "Documenter le but du projet et les contacts responsables."
          ],
          en: [
            "Never use a personal account for a temporary lab.",
            "Avoid Owner and Editor outside strict administration.",
            "Document the project purpose and accountable contacts."
          ]
        }
      }
    ],
    examples: {
      fr: [
        "Un projet qwiklabs-gcp-* sert a isoler un lab de 40 minutes; il peut etre supprime automatiquement.",
        "Une equipe production peut avoir un folder prod avec policies, budgets, audit logs et projets separes par application."
      ],
      en: [
        "A qwiklabs-gcp-* project isolates a 40-minute lab and can be automatically deleted.",
        "A production team can use a prod folder with policies, budgets, audit logs, and projects separated by application."
      ]
    },
    guidedLab: {
      title: { fr: "Audit rapide d'un projet", en: "Quick project audit" },
      objective: {
        fr: "Retrouver les identifiants du projet, verifier IAM et confirmer les API actives.",
        en: "Find project identifiers, review IAM, and confirm enabled APIs."
      },
      steps: [
        {
          id: "project-identity",
          title: { fr: "Identifier le projet", en: "Identify the project" },
          detail: {
            fr: "Ouvre IAM & Admin > Settings et note project name, project ID et project number.",
            en: "Open IAM & Admin > Settings and note project name, project ID, and project number."
          }
        },
        {
          id: "iam-review",
          title: { fr: "Lire IAM", en: "Read IAM" },
          detail: {
            fr: "Ouvre IAM, repere les principals et note les roles trop larges.",
            en: "Open IAM, identify principals, and note overly broad roles."
          }
        },
        {
          id: "api-check",
          title: { fr: "Verifier les API", en: "Check APIs" },
          detail: {
            fr: "Ouvre APIs & Services et confirme que seules les API utiles au lab sont activees.",
            en: "Open APIs & Services and confirm only lab-required APIs are enabled."
          }
        }
      ]
    },
    failureFeedback: {
      fr: "Revois la difference entre projet et ressource, puis refais le quiz en te concentrant sur IAM et les identifiants de projet.",
      en: "Review the difference between project and resource, then retake the quiz focusing on IAM and project identifiers."
    }
  },
  "vpc-basics": {
    estimatedTime: { fr: "60 minutes", en: "60 minutes" },
    objectives: {
      fr: [
        "Expliquer pourquoi un VPC est global et un subnet regional.",
        "Lire les routes et firewall rules creees par un reseau auto mode.",
        "Relier une VM au bon reseau et tester la connectivite."
      ],
      en: [
        "Explain why a VPC is global and a subnet is regional.",
        "Read routes and firewall rules created by an auto mode network.",
        "Attach a VM to the right network and test connectivity."
      ]
    },
    prerequisites: {
      fr: ["Module Fondations Google Cloud valide.", "Notions CIDR: adresse IP, masque, plage."],
      en: ["Google Cloud Foundations module passed.", "CIDR basics: IP address, mask, range."]
    },
    lessonSections: [
      {
        id: "vpc-scope",
        title: { fr: "VPC global, subnets regionaux", en: "Global VPC, regional subnets" },
        body: {
          fr: "Un VPC Google Cloud est une ressource globale. Il contient des sous-reseaux regionaux, chacun avec sa plage CIDR. Une VM obtient son IP interne depuis le subnet de sa zone.",
          en: "A Google Cloud VPC is a global resource. It contains regional subnets, each with a CIDR range. A VM gets its internal IP from the subnet of its zone."
        },
        bullets: {
          fr: ["Le nom du VPC est global au projet.", "Les subnets portent les plages IP internes.", "Les plages CIDR ne doivent pas se chevaucher."],
          en: ["The VPC name is global within the project.", "Subnets carry internal IP ranges.", "CIDR ranges must not overlap."]
        }
      },
      {
        id: "routes-firewall",
        title: { fr: "Routes et firewall", en: "Routes and firewall" },
        body: {
          fr: "Les routes disent ou envoyer les paquets. Les firewall rules decident si le trafic est autorise. Les routes systeme connectent les subnets du meme VPC; les regles implied bloquent l'ingress et autorisent l'egress.",
          en: "Routes decide where packets go. Firewall rules decide whether traffic is allowed. System routes connect subnets in the same VPC; implied rules block ingress and allow egress."
        },
        bullets: {
          fr: ["allow-ssh autorise tcp:22.", "allow-icmp autorise ping externe.", "allow-custom autorise le trafic interne du VPC."],
          en: ["allow-ssh allows tcp:22.", "allow-icmp allows external ping.", "allow-custom allows internal VPC traffic."]
        }
      },
      {
        id: "connectivity-tests",
        title: { fr: "Tests de connectivite", en: "Connectivity tests" },
        body: {
          fr: "Tester un reseau, c'est tester plusieurs couches: existence du VPC, subnet, IP interne, route, firewall, service ecoute et chemin retour.",
          en: "Testing a network means testing layers: VPC existence, subnet, internal IP, route, firewall, listening service, and return path."
        },
        bullets: {
          fr: ["Ping valide ICMP, pas TCP.", "SSH valide tcp:22 et les cles.", "Une IP externe ephemeral peut changer apres arret."],
          en: ["Ping validates ICMP, not TCP.", "SSH validates tcp:22 and keys.", "An ephemeral external IP can change after stop."]
        }
      }
    ],
    examples: {
      fr: ["mynet-us-vm en us-west1-a utilise le subnet us-west1.", "Supprimer allow-icmp casse le ping vers l'IP externe mais pas forcement l'IP interne."],
      en: ["mynet-us-vm in us-west1-a uses the us-west1 subnet.", "Deleting allow-icmp breaks ping to the external IP but not necessarily the internal IP."]
    },
    guidedLab: {
      title: { fr: "VPC auto mode et deux VM", en: "Auto mode VPC and two VMs" },
      objective: { fr: "Creer mynetwork, deux VM et tester ping interne/externe.", en: "Create mynetwork, two VMs, and test internal/external ping." },
      steps: [
        { id: "delete-default", title: { fr: "Nettoyer default", en: "Clean default" }, detail: { fr: "Supprime les regles default puis le VPC default.", en: "Delete default rules, then the default VPC." } },
        { id: "create-network", title: { fr: "Creer mynetwork", en: "Create mynetwork" }, detail: { fr: "Mode Automatic, toutes les regles standard cochees.", en: "Automatic mode, all standard rules selected." } },
        { id: "test-vms", title: { fr: "Tester les VM", en: "Test VMs" }, detail: { fr: "SSH vers la premiere VM, puis ping l'IP interne et externe de la seconde.", en: "SSH to the first VM, then ping the second VM internal and external IPs." } }
      ]
    },
    failureFeedback: {
      fr: "Reprends les differences VPC/subnet/route/firewall. Les erreurs viennent souvent de la portee regionale du subnet ou de la regle ICMP.",
      en: "Review VPC/subnet/route/firewall differences. Mistakes often come from subnet regional scope or the ICMP rule."
    }
  },
  "compute-and-storage": {
    estimatedTime: { fr: "55 minutes", en: "55 minutes" },
    objectives: {
      fr: ["Choisir entre VM, stockage objet et base relationnelle.", "Comprendre IP externe, disque boot et image OS.", "Relier une application simple a Cloud Storage et Cloud SQL."],
      en: ["Choose between VM, object storage, and relational database.", "Understand external IP, boot disk, and OS image.", "Connect a simple app to Cloud Storage and Cloud SQL."]
    },
    prerequisites: {
      fr: ["VPC et firewall basics.", "Notions Linux: SSH, fichier, service web."],
      en: ["VPC and firewall basics.", "Linux basics: SSH, file, web service."]
    },
    lessonSections: [
      {
        id: "compute-engine",
        title: { fr: "Compute Engine", en: "Compute Engine" },
        body: { fr: "Compute Engine donne des VM configurables: machine type, image, disque, interface reseau, service account et options de securite.", en: "Compute Engine provides configurable VMs: machine type, image, disk, network interface, service account, and security options." },
        bullets: { fr: ["e2-micro est adapte aux labs.", "Le disque boot contient le systeme.", "Les tags reseau peuvent cibler des firewall rules."], en: ["e2-micro suits labs.", "The boot disk contains the OS.", "Network tags can target firewall rules."] }
      },
      {
        id: "storage",
        title: { fr: "Cloud Storage", en: "Cloud Storage" },
        body: { fr: "Cloud Storage stocke des objets dans des buckets. Ce n'est ni un disque Linux ni une base SQL: il sert aux fichiers, images, backups et datasets.", en: "Cloud Storage stores objects in buckets. It is not a Linux disk or SQL database: it serves files, images, backups, and datasets." },
        bullets: { fr: ["Choisir la classe selon la frequence d'acces.", "Controler l'acces avec IAM ou signed URLs.", "Eviter les buckets publics par defaut."], en: ["Choose class by access frequency.", "Control access with IAM or signed URLs.", "Avoid public buckets by default."] }
      },
      {
        id: "cloud-sql",
        title: { fr: "Cloud SQL", en: "Cloud SQL" },
        body: { fr: "Cloud SQL est une base relationnelle managee. Il faut penser reseau, utilisateurs, sauvegardes, haute disponibilite et secrets.", en: "Cloud SQL is a managed relational database. You must consider network, users, backups, high availability, and secrets." },
        bullets: { fr: ["Ne jamais mettre les mots de passe dans le code.", "Limiter les IP autorisees.", "Preferer Secret Manager pour les credentials."], en: ["Never put passwords in code.", "Limit authorized IPs.", "Prefer Secret Manager for credentials."] }
      }
    ],
    examples: {
      fr: ["Une VM Apache/PHP sert le site, un bucket stocke l'image, Cloud SQL garde les donnees.", "Une IP externe permet le test rapide, mais un load balancer est preferable en production."],
      en: ["An Apache/PHP VM serves the site, a bucket stores the image, Cloud SQL keeps data.", "An external IP enables quick testing, but a load balancer is preferable in production."]
    },
    guidedLab: {
      title: { fr: "Application simple VM + Storage + SQL", en: "Simple VM + Storage + SQL app" },
      objective: { fr: "Servir une page web, afficher une image bucket et lire une base SQL.", en: "Serve a web page, display a bucket image, and read a SQL database." },
      steps: [
        { id: "create-vm", title: { fr: "Creer la VM", en: "Create the VM" }, detail: { fr: "Debian, e2-micro, firewall HTTP si necessaire.", en: "Debian, e2-micro, HTTP firewall if required." } },
        { id: "create-bucket", title: { fr: "Ajouter le bucket", en: "Add the bucket" }, detail: { fr: "Cree un bucket regional et uploade une image de test.", en: "Create a regional bucket and upload a test image." } },
        { id: "connect-sql", title: { fr: "Connecter Cloud SQL", en: "Connect Cloud SQL" }, detail: { fr: "Cree une base MySQL, un user limite et teste la connexion.", en: "Create a MySQL database, limited user, and test the connection." } }
      ]
    },
    failureFeedback: {
      fr: "Revois la fonction de chaque service. Si tu confonds bucket, disque VM et Cloud SQL, refais la section stockage.",
      en: "Review each service purpose. If you confuse bucket, VM disk, and Cloud SQL, repeat the storage section."
    }
  },
  "firewall-identity": {
    estimatedTime: { fr: "50 minutes", en: "50 minutes" },
    objectives: {
      fr: ["Cibler les firewall rules par service account.", "Modeliser les flux microservices.", "Justifier source, cible, protocole, port et priorite."],
      en: ["Target firewall rules by service account.", "Model microservice flows.", "Justify source, target, protocol, port, and priority."]
    },
    prerequisites: { fr: ["VPC/firewall basics.", "Comprendre service accounts."], en: ["VPC/firewall basics.", "Understand service accounts."] },
    lessonSections: [
      { id: "identity-targeting", title: { fr: "Ciblage par identite", en: "Identity targeting" }, body: { fr: "Les IP changent, les tags peuvent etre mal appliques, mais un service account exprime l'identite du workload.", en: "IPs change, tags can be misapplied, but a service account expresses workload identity." }, bullets: { fr: ["Source service account = qui initie.", "Target service account = qui reçoit.", "La regle suit l'identite, pas l'adresse."], en: ["Source service account = who initiates.", "Target service account = who receives.", "The rule follows identity, not address."] } },
      { id: "flow-table", title: { fr: "Table de flux", en: "Flow table" }, body: { fr: "Avant de creer les regles, ecris une table: MS1 -> MS2 tcp:8443, MS2 -> MS3 tcp:8663, MS3 -> MS1 tcp:8883.", en: "Before creating rules, write a table: MS1 -> MS2 tcp:8443, MS2 -> MS3 tcp:8663, MS3 -> MS1 tcp:8883." }, bullets: { fr: ["Un flux = source, destination, port, justification.", "Toute absence de justification doit etre bloquee.", "Les priorites plus basses numeriquement gagnent."], en: ["A flow = source, destination, port, justification.", "Any unjustified flow must be blocked.", "Numerically lower priorities win."] } },
      { id: "audit", title: { fr: "Audit et logs", en: "Audit and logs" }, body: { fr: "Les firewall logs permettent de prouver quelle regle a autorise ou refuse un trafic. Sans logs, le diagnostic devient lent.", en: "Firewall logs prove which rule allowed or denied traffic. Without logs, diagnosis becomes slow." }, bullets: { fr: ["Activer les logs sur les regles sensibles.", "Nommer les regles selon le flux.", "Tester avec curl ou nc."], en: ["Enable logs on sensitive rules.", "Name rules by flow.", "Test with curl or nc."] } }
    ],
    examples: { fr: ["Autoriser seulement sa-ms1 vers sa-ms2 sur tcp:8443.", "Refuser un appel direct de ms1 vers ms3 car le flux attendu passe par ms2."], en: ["Allow only sa-ms1 to sa-ms2 on tcp:8443.", "Deny direct ms1 to ms3 because expected flow goes through ms2."] },
    guidedLab: { title: { fr: "Firewall microservices", en: "Microservice firewall" }, objective: { fr: "Creer trois regles basees sur service accounts.", en: "Create three service-account-based rules." }, steps: [
      { id: "accounts", title: { fr: "Creer S1/S2/S3", en: "Create S1/S2/S3" }, detail: { fr: "Associe chaque VM au service account correspondant.", en: "Attach each VM to its matching service account." } },
      { id: "rules", title: { fr: "Creer les regles", en: "Create rules" }, detail: { fr: "Autorise uniquement les ports documentes.", en: "Allow only documented ports." } },
      { id: "test", title: { fr: "Tester les chemins", en: "Test paths" }, detail: { fr: "Verifie les flux autorises et un flux interdit.", en: "Verify allowed flows and one denied flow." } }
    ] },
    failureFeedback: { fr: "Reprends la notion source/target: beaucoup d'erreurs viennent d'une inversion entre initiateur et recepteur.", en: "Review source/target: many errors come from reversing initiator and receiver." }
  },
  "load-balancing-cdn-dns": {
    estimatedTime: { fr: "65 minutes", en: "65 minutes" },
    objectives: { fr: ["Relier DNS, load balancer, backend et CDN.", "Comprendre les health checks.", "Savoir quand activer Cloud CDN."], en: ["Connect DNS, load balancer, backend, and CDN.", "Understand health checks.", "Know when to enable Cloud CDN."] },
    prerequisites: { fr: ["HTTP/HTTPS basics.", "Notions de backend et endpoint."], en: ["HTTP/HTTPS basics.", "Backend and endpoint concepts."] },
    lessonSections: [
      { id: "dns-entry", title: { fr: "Entree DNS", en: "DNS entry" }, body: { fr: "DNS traduit un nom public vers une adresse ou un endpoint. Pour une application globale, le DNS pointe souvent vers l'IP du load balancer.", en: "DNS translates a public name to an address or endpoint. For a global app, DNS often points to the load balancer IP." }, bullets: { fr: ["A/AAAA pour IP.", "CNAME pour alias.", "TTL impacte la propagation."], en: ["A/AAAA for IP.", "CNAME for aliases.", "TTL impacts propagation."] } },
      { id: "lb-health", title: { fr: "Load balancer et health checks", en: "Load balancer and health checks" }, body: { fr: "Le load balancer ne doit envoyer du trafic qu'a des backends sains. Les health checks valident chemin, protocole, port et reponse.", en: "The load balancer should send traffic only to healthy backends. Health checks validate path, protocol, port, and response." }, bullets: { fr: ["Un backend unhealthy ne reçoit plus de trafic.", "La firewall rule doit autoriser les health checks.", "Les certificats TLS sont sur le frontend HTTPS."], en: ["An unhealthy backend stops receiving traffic.", "Firewall must allow health checks.", "TLS certificates sit on the HTTPS frontend."] } },
      { id: "cdn-cache", title: { fr: "Cache CDN", en: "CDN cache" }, body: { fr: "Cloud CDN reduit la latence pour les contenus cacheables: images, CSS, JS, fichiers statiques. Il ne corrige pas un backend lent sur contenu non cacheable.", en: "Cloud CDN reduces latency for cacheable content: images, CSS, JS, static files. It does not fix a slow backend for non-cacheable content." }, bullets: { fr: ["Definir cache headers.", "Purger seulement quand necessaire.", "Observer hit ratio et latence."], en: ["Set cache headers.", "Purge only when needed.", "Observe hit ratio and latency."] } }
    ],
    examples: { fr: ["www.example.com -> IP load balancer -> backend service -> MIG.", "Cloud CDN garde les images produit proches des utilisateurs."], en: ["www.example.com -> load balancer IP -> backend service -> MIG.", "Cloud CDN keeps product images close to users."] },
    guidedLab: { title: { fr: "Site public accelere", en: "Accelerated public site" }, objective: { fr: "Publier un backend HTTP via load balancer et CDN.", en: "Publish an HTTP backend through load balancer and CDN." }, steps: [
      { id: "backend", title: { fr: "Creer le backend", en: "Create backend" }, detail: { fr: "Prepare une VM ou un groupe backend avec une page HTTP.", en: "Prepare a VM or backend group with an HTTP page." } },
      { id: "lb", title: { fr: "Configurer LB", en: "Configure LB" }, detail: { fr: "Frontend, backend service, health check et firewall.", en: "Frontend, backend service, health check, and firewall." } },
      { id: "cdn", title: { fr: "Activer CDN", en: "Enable CDN" }, detail: { fr: "Teste les headers cache et observe les reponses.", en: "Test cache headers and observe responses." } }
    ] },
    failureFeedback: { fr: "Revois la chaine DNS -> LB -> backend. Si tu rates, dessine le chemin complet avant de repondre.", en: "Review DNS -> LB -> backend. If you fail, draw the complete path before answering." }
  },
  "gke-run-serverless": {
    estimatedTime: { fr: "60 minutes", en: "60 minutes" },
    objectives: { fr: ["Comparer GKE et Cloud Run.", "Identifier le bon runtime pour un conteneur.", "Comprendre service, ingress et scaling."], en: ["Compare GKE and Cloud Run.", "Identify the right runtime for a container.", "Understand service, ingress, and scaling."] },
    prerequisites: { fr: ["Bases conteneurs Docker.", "Notions HTTP et variables d'environnement."], en: ["Docker container basics.", "HTTP and environment variable concepts."] },
    lessonSections: [
      { id: "cloud-run", title: { fr: "Cloud Run", en: "Cloud Run" }, body: { fr: "Cloud Run execute des conteneurs serverless. Il est ideal pour API, webhooks et services HTTP qui doivent scaler sans gerer de cluster.", en: "Cloud Run runs serverless containers. It is ideal for APIs, webhooks, and HTTP services that must scale without managing clusters." }, bullets: { fr: ["Scaling automatique.", "Revision par deploiement.", "IAM peut controler l'invocation."], en: ["Automatic scaling.", "Revision per deployment.", "IAM can control invocation."] } },
      { id: "gke", title: { fr: "GKE", en: "GKE" }, body: { fr: "GKE donne Kubernetes manage pour orchestrer des workloads complexes: deployments, services, ingress, autoscaling, policies et reseaux avances.", en: "GKE provides managed Kubernetes for complex workloads: deployments, services, ingress, autoscaling, policies, and advanced networking." }, bullets: { fr: ["Plus de controle.", "Plus d'operations.", "Adapté aux plateformes internes."], en: ["More control.", "More operations.", "Suited for internal platforms."] } },
      { id: "choice", title: { fr: "Choisir le runtime", en: "Choose the runtime" }, body: { fr: "Le choix depend du controle voulu, du trafic, des contraintes reseau et de la maturite operationnelle.", en: "The choice depends on required control, traffic, network constraints, and operational maturity." }, bullets: { fr: ["Cloud Run pour simplicité.", "GKE pour orchestration fine.", "Functions pour evenements simples."], en: ["Cloud Run for simplicity.", "GKE for fine orchestration.", "Functions for simple events."] } }
    ],
    examples: { fr: ["Webhook paiement sur Cloud Run.", "Plateforme multi-services avec ingress prive sur GKE."], en: ["Payment webhook on Cloud Run.", "Multi-service platform with private ingress on GKE."] },
    guidedLab: { title: { fr: "Deployer un conteneur", en: "Deploy a container" }, objective: { fr: "Comparer un deploiement Cloud Run et un service GKE.", en: "Compare Cloud Run deployment and GKE service." }, steps: [
      { id: "image", title: { fr: "Preparer l'image", en: "Prepare image" }, detail: { fr: "Choisis une image HTTP simple.", en: "Choose a simple HTTP image." } },
      { id: "run", title: { fr: "Deployer Cloud Run", en: "Deploy Cloud Run" }, detail: { fr: "Teste URL, logs et revisions.", en: "Test URL, logs, and revisions." } },
      { id: "gke", title: { fr: "Comparer GKE", en: "Compare GKE" }, detail: { fr: "Observe deployment, service et ingress.", en: "Observe deployment, service, and ingress." } }
    ] },
    failureFeedback: { fr: "Revois le niveau d'abstraction: Cloud Run cache l'infra, GKE expose Kubernetes.", en: "Review abstraction level: Cloud Run hides infrastructure, GKE exposes Kubernetes." }
  },
  "hybrid-connectivity": {
    estimatedTime: { fr: "70 minutes", en: "70 minutes" },
    objectives: { fr: ["Comparer VPN et Interconnect.", "Comprendre BGP avec Cloud Router.", "Planifier des CIDR sans chevauchement."], en: ["Compare VPN and Interconnect.", "Understand BGP with Cloud Router.", "Plan non-overlapping CIDRs."] },
    prerequisites: { fr: ["Routage IP.", "Notions on-premises et cloud."], en: ["IP routing.", "On-premises and cloud concepts."] },
    lessonSections: [
      { id: "vpn-interconnect", title: { fr: "VPN vs Interconnect", en: "VPN vs Interconnect" }, body: { fr: "Cloud VPN chiffre le trafic sur Internet. Interconnect fournit une connectivite dediee pour debit, latence et fiabilite plus previsible.", en: "Cloud VPN encrypts traffic over the internet. Interconnect provides dedicated connectivity for more predictable throughput, latency, and reliability." }, bullets: { fr: ["VPN est rapide a lancer.", "Interconnect demande plus de preparation.", "HA VPN utilise deux tunnels par interface."], en: ["VPN is quick to start.", "Interconnect requires more planning.", "HA VPN uses two tunnels per interface."] } },
      { id: "bgp", title: { fr: "BGP et Cloud Router", en: "BGP and Cloud Router" }, body: { fr: "Cloud Router echange des routes dynamiques avec l'equipement pair. Il evite de maintenir manuellement toutes les routes hybrides.", en: "Cloud Router exchanges dynamic routes with the peer device. It avoids manually maintaining every hybrid route." }, bullets: { fr: ["ASN local et pair.", "Annonces de prefixes.", "Priorites et preference de chemin."], en: ["Local and peer ASN.", "Prefix advertisements.", "Priorities and path preference."] } },
      { id: "cidr", title: { fr: "Plan CIDR", en: "CIDR plan" }, body: { fr: "Un design hybride echoue souvent a cause de plages qui se chevauchent. Le plan IP doit prevoir croissance, regions et environnements.", en: "Hybrid design often fails because ranges overlap. The IP plan must account for growth, regions, and environments." }, bullets: { fr: ["Reserver des blocs par region.", "Documenter les exceptions.", "Valider avant peering/VPN."], en: ["Reserve blocks by region.", "Document exceptions.", "Validate before peering/VPN."] } }
    ],
    examples: { fr: ["Siege 10.10.0.0/16 vers VPC 10.40.0.0/16 via HA VPN.", "Interconnect pour workloads regulierement synchronises."], en: ["HQ 10.10.0.0/16 to VPC 10.40.0.0/16 via HA VPN.", "Interconnect for regularly synchronized workloads."] },
    guidedLab: { title: { fr: "Design hybride", en: "Hybrid design" }, objective: { fr: "Produire une table CIDR, routes et choix VPN/Interconnect.", en: "Produce a CIDR, routes, and VPN/Interconnect decision table." }, steps: [
      { id: "cidr", title: { fr: "Lister CIDR", en: "List CIDRs" }, detail: { fr: "Note on-prem, VPC actuel et VPC futur.", en: "Note on-prem, current VPC, and future VPC." } },
      { id: "routes", title: { fr: "Dessiner routes", en: "Draw routes" }, detail: { fr: "Ajoute next hop et propagation dynamique.", en: "Add next hop and dynamic propagation." } },
      { id: "resilience", title: { fr: "Prevoir HA", en: "Plan HA" }, detail: { fr: "Ajoute tunnels redondants et procedure de bascule.", en: "Add redundant tunnels and failover procedure." } }
    ] },
    failureFeedback: { fr: "Revois VPN, Interconnect et Cloud Router ensemble: le produit de connectivite et le routage sont deux sujets lies mais differents.", en: "Review VPN, Interconnect, and Cloud Router together: connectivity product and routing are related but different topics." }
  },
  "hybrid-dns": {
    estimatedTime: { fr: "50 minutes", en: "50 minutes" },
    objectives: { fr: ["Concevoir une resolution DNS entre VPC et on-prem.", "Eviter les boucles de forwarding.", "Choisir zone privee, forwarding ou peering."], en: ["Design DNS resolution between VPC and on-prem.", "Avoid forwarding loops.", "Choose private zone, forwarding, or peering."] },
    prerequisites: { fr: ["Bases DNS: A, CNAME, resolver, zone.", "Connectivite hybride fonctionnelle."], en: ["DNS basics: A, CNAME, resolver, zone.", "Working hybrid connectivity."] },
    lessonSections: [
      { id: "patterns", title: { fr: "Patterns DNS", en: "DNS patterns" }, body: { fr: "Une zone privee repond dans Google Cloud. Une policy de forwarding envoie certaines requetes vers on-prem. Le peering DNS partage la resolution entre VPC.", en: "A private zone answers inside Google Cloud. A forwarding policy sends some queries to on-prem. DNS peering shares resolution across VPCs." }, bullets: { fr: ["Private zone pour noms internes.", "Forwarding pour domaines on-prem.", "Peering pour VPC separes."], en: ["Private zone for internal names.", "Forwarding for on-prem domains.", "Peering for separate VPCs."] } },
      { id: "loop-risk", title: { fr: "Risque de boucle", en: "Loop risk" }, body: { fr: "Une boucle DNS apparait quand deux resolvers se renvoient la meme zone. Cela cree delais et SERVFAIL difficiles a diagnostiquer.", en: "A DNS loop appears when two resolvers forward the same zone back to each other. It creates delays and hard-to-diagnose SERVFAIL." }, bullets: { fr: ["Tracer le chemin de resolution.", "Limiter les zones transferees.", "Tester avec dig/nslookup."], en: ["Trace resolution path.", "Limit forwarded zones.", "Test with dig/nslookup."] } },
      { id: "operations", title: { fr: "Operations", en: "Operations" }, body: { fr: "Le DNS hybride doit etre documente comme un service critique. Les changements de zone doivent etre revus et testes.", en: "Hybrid DNS must be documented as a critical service. Zone changes must be reviewed and tested." }, bullets: { fr: ["Surveiller latence resolver.", "Documenter ownership de domaine.", "Prevoir rollback."], en: ["Monitor resolver latency.", "Document domain ownership.", "Plan rollback."] } }
    ],
    examples: { fr: ["corp.local forwarde vers on-prem, svc.gcp.internal reste dans Cloud DNS.", "Deux VPC partagent une zone via DNS peering."], en: ["corp.local forwards to on-prem, svc.gcp.internal stays in Cloud DNS.", "Two VPCs share a zone through DNS peering."] },
    guidedLab: { title: { fr: "Resolution hybride", en: "Hybrid resolution" }, objective: { fr: "Designer un flux DNS sans boucle.", en: "Design a DNS flow without loops." }, steps: [
      { id: "zones", title: { fr: "Identifier zones", en: "Identify zones" }, detail: { fr: "Liste domaines cloud et on-prem.", en: "List cloud and on-prem domains." } },
      { id: "forward", title: { fr: "Placer forwarding", en: "Place forwarding" }, detail: { fr: "Decide quelles requetes sortent du VPC.", en: "Decide which queries leave the VPC." } },
      { id: "test", title: { fr: "Tester", en: "Test" }, detail: { fr: "Utilise dig depuis une VM et depuis on-prem.", en: "Use dig from a VM and from on-prem." } }
    ] },
    failureFeedback: { fr: "Revois zone privee, forwarding et peering. Le mot cle est direction: qui interroge qui ?", en: "Review private zone, forwarding, and peering. The key word is direction: who queries whom?" }
  },
  "monitoring-troubleshooting": {
    estimatedTime: { fr: "60 minutes", en: "60 minutes" },
    objectives: { fr: ["Diagnostiquer par couches.", "Utiliser logs, routes et Connectivity Tests.", "Construire une preuve avant correction."], en: ["Diagnose by layers.", "Use logs, routes, and Connectivity Tests.", "Build evidence before fixing."] },
    prerequisites: { fr: ["VPC, firewall et DNS.", "Savoir reproduire un incident simple."], en: ["VPC, firewall, and DNS.", "Know how to reproduce a simple incident."] },
    lessonSections: [
      { id: "layered-method", title: { fr: "Methode par couches", en: "Layered method" }, body: { fr: "Ne saute pas directement a l'application. Verifie DNS, route, firewall, service ecoute, health check et logs.", en: "Do not jump directly to the application. Verify DNS, route, firewall, listening service, health check, and logs." }, bullets: { fr: ["DNS: le nom resout-il ?", "Route: le next hop existe-t-il ?", "Firewall: le port est-il autorise ?"], en: ["DNS: does the name resolve?", "Route: does the next hop exist?", "Firewall: is the port allowed?"] } },
      { id: "evidence", title: { fr: "Preuves", en: "Evidence" }, body: { fr: "Un bon diagnostic garde les commandes, timestamps, IP source/destination, regles touchees et resultat attendu/observe.", en: "A good diagnosis keeps commands, timestamps, source/destination IPs, matched rules, and expected/observed result." }, bullets: { fr: ["Copier les logs utiles.", "Capturer le test de connectivite.", "Nommer l'hypothese."], en: ["Copy useful logs.", "Capture the connectivity test.", "Name the hypothesis."] } },
      { id: "fix-verify", title: { fr: "Corriger et verifier", en: "Fix and verify" }, body: { fr: "Une correction reseau doit etre minimale et testee. Si tu ouvres 0.0.0.0/0 pour tout, tu as masque le probleme au lieu de le resoudre.", en: "A network fix must be minimal and tested. If you open 0.0.0.0/0 for everything, you masked the issue instead of solving it." }, bullets: { fr: ["Changer une variable a la fois.", "Retester le flux exact.", "Documenter le rollback."], en: ["Change one variable at a time.", "Retest the exact flow.", "Document rollback."] } }
    ],
    examples: { fr: ["Un backend unhealthy vient d'un port health check bloque.", "Un nom DNS correct pointe vers une IP sans route retour."], en: ["An unhealthy backend comes from a blocked health-check port.", "A correct DNS name points to an IP with no return route."] },
    guidedLab: { title: { fr: "Incident reseau", en: "Network incident" }, objective: { fr: "Trouver la couche qui bloque un flux HTTP.", en: "Find the layer blocking an HTTP flow." }, steps: [
      { id: "reproduce", title: { fr: "Reproduire", en: "Reproduce" }, detail: { fr: "Lance curl/ping/dig et note les erreurs.", en: "Run curl/ping/dig and note errors." } },
      { id: "inspect", title: { fr: "Inspecter", en: "Inspect" }, detail: { fr: "Lis routes, firewall logs et health checks.", en: "Read routes, firewall logs, and health checks." } },
      { id: "prove", title: { fr: "Prouver", en: "Prove" }, detail: { fr: "Corrige une regle et reteste le meme flux.", en: "Fix one rule and retest the same flow." } }
    ] },
    failureFeedback: { fr: "Reprends la methode par couches. Si tu reponds au hasard, dessine le chemin paquet avant le prochain essai.", en: "Review the layered method. If you guess, draw the packet path before the next attempt." }
  },
  "edge-security": {
    estimatedTime: { fr: "55 minutes", en: "55 minutes" },
    objectives: { fr: ["Positionner Cloud Armor.", "Comprendre WAF, rate limit et geo/IP rules.", "Relier securite edge et load balancing."], en: ["Position Cloud Armor.", "Understand WAF, rate limit, and geo/IP rules.", "Connect edge security and load balancing."] },
    prerequisites: { fr: ["Load balancing HTTP(S).", "Bases OWASP et trafic web."], en: ["HTTP(S) load balancing.", "OWASP and web traffic basics."] },
    lessonSections: [
      { id: "edge-layer", title: { fr: "Couche edge", en: "Edge layer" }, body: { fr: "La securite edge filtre avant les backends. Cloud Armor s'attache aux backend services derriere un load balancer HTTP(S).", en: "Edge security filters before backends. Cloud Armor attaches to backend services behind an HTTP(S) load balancer." }, bullets: { fr: ["Bloquer IP ou pays.", "Appliquer WAF preconfigure.", "Limiter le taux de requetes."], en: ["Block IP or countries.", "Apply preconfigured WAF.", "Rate-limit requests."] } },
      { id: "policy-design", title: { fr: "Design de policy", en: "Policy design" }, body: { fr: "Une bonne policy commence en mode observation, mesure les faux positifs, puis passe en blocage sur des regles ciblees.", en: "A good policy starts in observation, measures false positives, then moves to blocking on targeted rules." }, bullets: { fr: ["Priorites explicites.", "Descriptions claires.", "Logs actives."], en: ["Explicit priorities.", "Clear descriptions.", "Logs enabled."] } },
      { id: "ops", title: { fr: "Operations securite", en: "Security operations" }, body: { fr: "Cloud Armor doit etre lie a alertes, dashboards et procedure d'urgence pour attaques DDoS ou scans agressifs.", en: "Cloud Armor must connect to alerts, dashboards, and emergency procedure for DDoS attacks or aggressive scans." }, bullets: { fr: ["Surveiller denies.", "Comparer baseline et pic.", "Prevoir exception temporaire."], en: ["Monitor denies.", "Compare baseline and spike.", "Plan temporary exception."] } }
    ],
    examples: { fr: ["Bloquer une vague de scans SQLi avec WAF.", "Rate limit sur /login pour reduire brute force."], en: ["Block SQLi scan wave with WAF.", "Rate-limit /login to reduce brute force."] },
    guidedLab: { title: { fr: "Policy Cloud Armor", en: "Cloud Armor policy" }, objective: { fr: "Concevoir une policy WAF defensive.", en: "Design a defensive WAF policy." }, steps: [
      { id: "baseline", title: { fr: "Baseline", en: "Baseline" }, detail: { fr: "Liste endpoints publics et trafic normal.", en: "List public endpoints and normal traffic." } },
      { id: "rules", title: { fr: "Regles", en: "Rules" }, detail: { fr: "Ajoute WAF, deny ciblé et rate limit.", en: "Add WAF, targeted deny, and rate limit." } },
      { id: "observe", title: { fr: "Observer", en: "Observe" }, detail: { fr: "Verifie logs et faux positifs.", en: "Check logs and false positives." } }
    ] },
    failureFeedback: { fr: "Revois ou Cloud Armor s'applique: ce n'est pas une regle firewall VPC, c'est une protection edge HTTP(S).", en: "Review where Cloud Armor applies: it is not a VPC firewall rule, it is HTTP(S) edge protection." }
  },
  "egress-nat-inspection": {
    estimatedTime: { fr: "60 minutes", en: "60 minutes" },
    objectives: { fr: ["Expliquer Cloud NAT pour VM privees.", "Comparer NAT, proxy et inspection IDS.", "Tracer les sorties Internet."], en: ["Explain Cloud NAT for private VMs.", "Compare NAT, proxy, and IDS inspection.", "Trace internet egress."] },
    prerequisites: { fr: ["Routes et subnets.", "Bases securite reseau."], en: ["Routes and subnets.", "Network security basics."] },
    lessonSections: [
      { id: "cloud-nat", title: { fr: "Cloud NAT", en: "Cloud NAT" }, body: { fr: "Cloud NAT permet a des VM sans IP externe de sortir vers Internet. Il ne permet pas l'ingress entrant vers ces VM.", en: "Cloud NAT lets VMs without external IPs reach the internet. It does not allow inbound ingress to those VMs." }, bullets: { fr: ["Associe a Cloud Router.", "Controle ports NAT.", "Garde les VM non exposees."], en: ["Associated with Cloud Router.", "Controls NAT ports.", "Keeps VMs unexposed."] } },
      { id: "proxy", title: { fr: "Proxy egress", en: "Egress proxy" }, body: { fr: "Un proxy ajoute controle applicatif: domaines autorises, authentification, inspection et journalisation plus riche.", en: "A proxy adds application control: allowed domains, authentication, inspection, and richer logging." }, bullets: { fr: ["Filtrer par domaine.", "Centraliser logs.", "Appliquer policy par equipe."], en: ["Filter by domain.", "Centralize logs.", "Apply policy by team."] } },
      { id: "ids", title: { fr: "Inspection IDS", en: "IDS inspection" }, body: { fr: "Cloud IDS aide a detecter menaces et comportements suspects. Il complete les controles, il ne remplace pas les firewall rules.", en: "Cloud IDS helps detect threats and suspicious behavior. It complements controls; it does not replace firewall rules." }, bullets: { fr: ["Surveiller signatures.", "Corréler avec logs.", "Prevoir procedure d'investigation."], en: ["Monitor signatures.", "Correlate with logs.", "Plan investigation procedure."] } }
    ],
    examples: { fr: ["VM privee telecharge des updates via Cloud NAT.", "Proxy autorise seulement les domaines SaaS approuves."], en: ["Private VM downloads updates through Cloud NAT.", "Proxy allows only approved SaaS domains."] },
    guidedLab: { title: { fr: "Sortie controlee", en: "Controlled egress" }, objective: { fr: "Designer une sortie Internet sans IP externe.", en: "Design internet egress without external IPs." }, steps: [
      { id: "private-vm", title: { fr: "VM privee", en: "Private VM" }, detail: { fr: "Cree une VM sans IP externe.", en: "Create a VM without external IP." } },
      { id: "nat", title: { fr: "Ajouter NAT", en: "Add NAT" }, detail: { fr: "Configure Cloud Router et Cloud NAT.", en: "Configure Cloud Router and Cloud NAT." } },
      { id: "logs", title: { fr: "Observer", en: "Observe" }, detail: { fr: "Teste curl et lis les logs egress.", en: "Test curl and read egress logs." } }
    ] },
    failureFeedback: { fr: "Revois ingress vs egress. Cloud NAT aide a sortir, pas a recevoir du trafic entrant.", en: "Review ingress vs egress. Cloud NAT helps outbound traffic, not inbound traffic." }
  },
  governance: {
    estimatedTime: { fr: "55 minutes", en: "55 minutes" },
    objectives: { fr: ["Comprendre hierarchical firewall policies.", "Standardiser les regles reseau.", "Mettre en place audit et exceptions."], en: ["Understand hierarchical firewall policies.", "Standardize network rules.", "Set up audit and exceptions."] },
    prerequisites: { fr: ["IAM/folders.", "Firewall rules avancees."], en: ["IAM/folders.", "Advanced firewall rules."] },
    lessonSections: [
      { id: "hierarchy", title: { fr: "Policies hierarchiques", en: "Hierarchical policies" }, body: { fr: "Les hierarchical firewall policies appliquent des regles a l'organisation ou aux folders. Elles imposent des standards avant les regles projet.", en: "Hierarchical firewall policies apply rules at organization or folder level. They enforce standards before project rules." }, bullets: { fr: ["Centraliser deny critiques.", "Deleguer le reste aux projets.", "Documenter priorites."], en: ["Centralize critical denies.", "Delegate the rest to projects.", "Document priorities."] } },
      { id: "standards", title: { fr: "Standards", en: "Standards" }, body: { fr: "La gouvernance transforme des decisions techniques en regles repetables: naming, ports autorises, logs, owners et revue de changement.", en: "Governance turns technical decisions into repeatable rules: naming, allowed ports, logs, owners, and change review." }, bullets: { fr: ["Exceptions datees.", "Owners identifies.", "Logs obligatoires sur flux sensibles."], en: ["Dated exceptions.", "Identified owners.", "Mandatory logs on sensitive flows."] } },
      { id: "review", title: { fr: "Revue continue", en: "Continuous review" }, body: { fr: "Un environnement cloud derive rapidement. Il faut detecter les regles trop larges, les projets oublies et les exceptions expirees.", en: "A cloud environment drifts quickly. You must detect overly broad rules, forgotten projects, and expired exceptions." }, bullets: { fr: ["Revue mensuelle.", "Alertes sur 0.0.0.0/0.", "Table de justification."], en: ["Monthly review.", "Alerts on 0.0.0.0/0.", "Justification table."] } }
    ],
    examples: { fr: ["Deny RDP depuis Internet au niveau folder production.", "Autoriser SSH seulement via bastion ou IAP."], en: ["Deny RDP from the internet at production folder level.", "Allow SSH only through bastion or IAP."] },
    guidedLab: { title: { fr: "Standard firewall", en: "Firewall standard" }, objective: { fr: "Creer une matrice de gouvernance reseau.", en: "Create a network governance matrix." }, steps: [
      { id: "inventory", title: { fr: "Inventaire", en: "Inventory" }, detail: { fr: "Liste flux publics, internes et admin.", en: "List public, internal, and admin flows." } },
      { id: "policy", title: { fr: "Policy", en: "Policy" }, detail: { fr: "Classe deny global, allow standard et exception.", en: "Classify global deny, standard allow, and exception." } },
      { id: "audit", title: { fr: "Audit", en: "Audit" }, detail: { fr: "Definis owner, expiration et log obligatoire.", en: "Define owner, expiration, and mandatory log." } }
    ] },
    failureFeedback: { fr: "Revois la difference entre regle projet et policy hierarchique. La gouvernance agit au-dessus du projet.", en: "Review the difference between project rule and hierarchical policy. Governance acts above the project." }
  }
};
